
CREATE TABLE IF NOT EXISTS `PESSOA_ENDERECO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `LOGRADOURO` varchar(50) NOT NULL,
  `CIDADE` varchar(50) DEFAULT NULL,
  `BAIRRO` varchar(50) DEFAULT NULL,
  `CEP` varchar(9) DEFAULT NULL,
  `PESSOA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`)
);

ALTER TABLE `PESSOA_ENDERECO` ADD FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA(ID);

